### ISSUE TITLE
How to set a variable from sql query to count rows in a table. 

### ISSUE THREAD

**Issue by Pprime1** [Pprime1/csasm#10]
https://stackoverflow.com/questions/67782233/javascript-node-js-set-a-variable-from-sql-query-to-count-rows-in-a-table

**Comment by judsona** [comment]
Ah yes, this problem :( everything in JavaScript likes to be asynchronous so it sucks when you need to get something in a synchronised fashion 

If you’re still having problems later tonight I’ll have a look :)

**Comment by Pprime1** [comment]
This issue has been resolved, I just need to learn how by unravelling the code structure again in server.js
