### ISSUE TITLE
GET https://csasm.herokuapp.com/favicon.ico 404 (Not Found)

### ISSUE THREAD

**Issue by Pprime1** [Pprime1/csasm#11]
Not sure where this is called from - presume one of the addins. It is an error that pops up in the client console log when the app is starting up.  Doesn't appear to cause any issues, but possibly worth tracking down and sorting one day.

**Comment by Pprime1** [comment]
Put a favicon.ico file in there and error has ceased. I can't see it being displayed anywhere. probably still worth working out where/what/why

**Comment by judsona** [comment]
favicon is the image the pops up in the corner of the tab you have open. It won't cause a problem
