### ISSUE TITLE
Database commands and startup code not running

### ISSUE THREAD

**Issue by Pprime1** [Pprime1/csasm#14]
Since the async rewrite it appears the startup command that deleted all residual rows from the player table is not being run. A rogue player entry is in the database table, but it will not delete. 

Related - the Heroku website "Datastore" pages to manage the postgres database allows dataclips in read-only mode only. No data updates here.

**Comment by judsona** [comment]
I'll look at the query see why it isn't deleting

**Comment by judsona** [comment]
Is this the rogue player? 

PS C:\Users\Andrew Judson\Software> heroku pg:psql -a csasm
--> Connecting to postgresql-triangular-74652
psql (13.2, server 13.3 (Ubuntu 13.3-1.pgdg20.04+1))
WARNING: Console code page (437) differs from Windows code page (1252)
         8-bit characters might not work correctly. See psql reference
         page "Notes for Windows users" for details.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

csasm::DATABASE=> select * from player;
          id          | room_id  |          updated_at           |                      location
----------------------+----------+-------------------------------+----------------------------------------------------
 NKj4Hv0HZoD1a-DWAAAB | GCALBURY | 2021-06-07 10:46:03.498421+00 | 0101000020110F000061C092AB58583BC0B9FE5D9FF9206340
(1 row)

**Comment by Pprime1** [comment]
actually no, that was my current test game. The rogue player was against GCTEST, but it has gone now. Maybe one of my attempts to get rid of it worked today

C:\Users\Peter>heroku login
heroku: Press any key to open up the browser to login or q to exit:
Opening browser to https://cli-auth.heroku.com/auth/cli/browser/3c93393e-8f1c-4d92-9e27-283a7670e78f?requestor=SFMyNTY.g2gDbQAAAA0xMTguMjA4LjI0LjcybgYAT_UV5nkBYgABUYA.sBNMQhJAVGpv6ZGtBO5hYQHHMdeNjRb-lVTFwOy3zJQ
Logging in... done
Logged in as pprime@live.com.au

C:\Users\Peter>heroku pg:psql -a csasm
--> Connecting to postgresql-triangular-74652
 !    The local psql command could not be located. For help installing psql, see
 !    https://devcenter.heroku.com/articles/heroku-postgresql#local-setup

C:\Users\Peter>


OK, I need to install something else. on it.

**Comment by judsona** [comment]
You need to install postgreSQL  onto your local machine. I installed Postgres 13, linked the bin directory up to my environment variables, and then heroku pg:psql has access to the psql command

**Comment by Pprime1** [comment]
OK, well that opens up an entirely new world to me - the heroku cli command prompt is finally useful to me. postgres v13 installed, path variable set, and I can run commands on my database. Cool!!

Which brings me back to the earlier issue that I cam currently ignoring. the md5 hash values of all tables that are checked in the database.js script (currently not being checked). compared to the hash stored in schemaversion.  I think I know how to update the values in the schemaversion table, but now need to work out how to work out what they should be set to.

**Comment by Pprime1** [comment]
this issue is resolved
