### ISSUE TITLE
Adding a leaflet map

### ISSUE THREAD

**Issue by Pprime1** [Pprime1/csasm#23]
Missing something I hope is obvious. To add in a leaflet map (cf: https://leafletjs.com/index.html ) the code has to be called **after** the <div> stateemnt in the html (ejs) file. 
Which is meaning it cannot be hosted in client.js? As this is included early in the index.ejs file. 
And so all the variables I want to use in order to have the map display useful and live changing content are not available.

Do i have to shift all the variables across to a different .js file just for displaying the map? Why is javascript suddenly all worried about the synchronous order of stuff?

index.ejs refers at present.

**Comment by judsona** [comment]
Your map code is declared after client.js is loaded.  So the variables aren’t available. 

If you made a map.js and did code there it would be useable  as long as you loaded it before client.js

**Comment by judsona** [comment]
I’m due to fly home tomorrow. I’ll have it look when I get home to see whether I got anything wrong

**Comment by judsona** [comment]
If you made a global variable / global methods you could also make reference to the map from client.js

**Comment by Pprime1** [comment]
Code flow logic might be the issue. 
In the INDEX.EJS file it calls client.js early on so that all the work can happen to populate the fields. But the mapid div is not placed until the bottom. Therefore the call to showmap.js has to be essentially at the bottom. Long after client.js is called. This thusly violates comment #2 above.

Maybe need to define mapid at the top of index.ejs, but not display it until the bottom? That way showmap.js could be called from within cleint.js instead, and thus be able to update values every ten seconds?


--------
yes, as proven by showing the MYID variable, it is undefined right at the very start of play, and is never looked at again. Need to have showmap.js code be called after client.js populates all the variables, or to have it update on a loop. So need to have showmap.js code inserted into the socket update functions, means it has to be called from client.js and so need to define the mapid div right at the beginning?



ALSO - for some reason the tiles are not displaying properly ... maybe mapbox isn't the right one to use afterall

**Comment by Pprime1** [comment]
delay putting stuff on the map until the first client.js|display_update call is run to have data in existence
and then update the player location and view every 5 seconds after that

`from showmap.js`
```
async function main() {
    const interval = setInterval(function() {
         if (is_running) { // we need to know that there is data populated before updating the map with it
	     if (!map_joined) { startmap()}; //start the map only once 
	     updatemap(); 
	  }
    }, 5000); // update map every 5 seconds with current player location.
};
main();

**Comment by Pprime1** [comment]
That seems to be holding/working steady now.

OK, so just the circles location data to sort out. 
 How to get the location of them converted back from 'GEOM' to 'WKT' (LatLng) format?
