### ISSUE TITLE
 Why is the Game Code not displaying on the main output?

### ISSUE THREAD

**Issue by Pprime1** [Pprime1/csasm#33]
something has changed in recent builds. Not sure when nor what. But Line #46 in index.ejs no longer displaying the #gameId value?
```
     <h1>Game Code: <span id="gameId" class="badge badge-secondary"></span>
```
possibly also missing form reward.ejs although we transmit it differently there (just can't test right at the moment).

It is set in client.js line#120, but maybe it is also needed in there around line #109? But I don't feel like it has ever been set up there and not sure how to do so anyway.  But reagrdless, it should be set once the code gets to line#120 and something isn't working there now.

cannot see what is wrong. :-(

**Comment by judsona** [comment]
I’ll give the code a peak tonight

**Comment by judsona** [comment]
You have two elements using the same id. Element id's should be unique through the html doucment. Make them unique and it should work again.

I would recommend only updating the current game id (in the span element) in the room_update event within client.js

`<input type="text" width:100="" class="form-control" id="gameId" aria-describedby="Game Code">`

and

`
<span id="gameId" class="badge badge-secondary"></span>
`

**Comment by Pprime1** [comment]
that seems to have done the trick. thankyou kindly
