### ISSUE TITLE
How to get the wp variable populated with data for use in index.ejs

### ISSUE THREAD

**Issue by Pprime1** [Pprime1/csasm#4]
Trying to get the 'waypoint-information' array of data that is sent from server.js for each room-update into the client js (mobcache-socketio.js) to be available for use/display in index.ejs. Ultimately will want to do some calculations on this data in the client but to start with just wanting to display it. 
The data is coming through as both console.log and the $#wpinfo variable is able to display it, but as a flat string and not in individual component parts.

**Comment by Pprime1** [comment]
Can get the data across from the client js by assigning a specific variable but how to display an array? Of potentially indeterminate length.

WORKS:         $("#wpname").text(waypoint_information[0].name);
$("#wpradius").text(waypoint_information[0].radius);        
$("#distance").text(waypoint_information[0].distance);

DOESN'T WORK:
<% for (var i = 0; i < 2 i++) { %> <tr><td><%= wp[i].name %> </td> <td&><%= wp[i].radius %>m</td>         <td><%= wp[i].distance %>m>/td> </tr>}%>

**Comment by judsona** [comment]
You’ve been busy :o 

waypoint_information.length for length. 

Use for array with < waypoint_information.length - 1.... I would loop over each object in JavaScript and tell jquery to push another entity into the page like I did for the chat app in the first iteration

**Comment by Pprime1** [comment]
In the end I gave up on doing it in the ejs file and created a big string containing the html table codes and substituting in values where I wanted them in the client.js. And just popped that into the ejs file. No idea if this is efficient or not but it works, so hooray.

truncated code snippet of what worked for me (in client.js):

  var $table = "<table border='1'>"
  $table += "<thead><tr><th>Player</th><th>Location</th></tr></thead><tbody>"
  for (var i = 0; i < display_information.length; i++) {
     $table += '<tr><td>' + display_information[i].id + '</td>'
     $table += '<td>' + display_information[i].name + '</td>'
  }
  $table += "</tr></tbody></table>"
  $('#displayinfo').empty().append($table);


and then in my index.ejs is:      <pre><span id="displayinfo"></span></pre>
