### ISSUE TITLE
Database is growing?

### ISSUE THREAD

**Issue by Pprime1** [Pprime1/csasm#43]
Database is designed to clear all game records and only persesitantly store game data .... minimal. 
But
``SELECT * FROM spatial_ref_sys;`` has 5800 rows. 
Something is creating lines in here and not purging them.

**Comment by Pprime1** [comment]
...or is that what it is supposed to be? dev database is the same size. Entries are all different to each other. May be not an issue

**Comment by judsona** [comment]
It is supposed to be there. It is used by postgis internally

**Comment by Pprime1** [comment]
good
