### ISSUE TITLE
Why is it crsshing now?

### ISSUE THREAD

**Issue by Pprime1** [Pprime1/csasm#8]
Wtf did i change?

**Comment by judsona** [comment]
Idk whether this is it. But It looks like some sql scripts are missing from the postgrad or folder. You should never delete historical scripts

that’s all I can determine from my phone

**Comment by judsona** [comment]
Oh and some of the files have changed. Postgrator checks the checksum for each file to ensure nothing has changed since it applied them

**Comment by Pprime1** [comment]
ok, seems poor practice to leave the compiled file littered with redundant scripts, but OK ... I will be wanting to add more games/waypoints into the scripts soon so may need some help weeding out which version of the files need updating and how to do so if they are checksummed.

Seems just recreating the deleted files doesn't fix the issue either. I may need significant help to undo that damage :-( 

It was working in the branch I created (was trying to get into that habit now instead of developing in the main branch), but maybe my branch somehow linked back to the files that were still in main at the time I was testing.

**Comment by Pprime1** [comment]
npm ERR!     /app/.npm/_logs/2021-05-30T22_27_05_119Z-debug.log

this is the build error. yet to work out how to get into that log file though. Not a valid file?

**Comment by judsona** [comment]
Heroku looks to be deleting the deployed app container before you can read the file.. very annoying

**Comment by judsona** [comment]
> ok, seems poor practice to leave the compiled file littered with redundant scripts, but OK ... I will be wanting to add more games/waypoints into the scripts soon so may need some help weeding out which version of the files need updating and how to do so if they are checksummed.
> 
> Seems just recreating the deleted files doesn't fix the issue either. I may need significant help to undo that damage :-(
> 
> It was working in the branch I created (was trying to get into that habit now instead of developing in the main branch), but maybe my branch somehow linked back to the files that were still in main at the time I was testing.

Yes, I know, they're left to show the "historical evolution" of the apps database.. and at one point I we had two versions running at same time so I left some redundant tables etc behind.

All good, I can help rebuild app :-)

**Comment by judsona** [comment]
Peter,

I've fixed it; retrieved md5 for each sql and compared to database, then applied differences, and restarted app dynos to confirm it is now running. :-)

Any future sql changes to database should create a new sql file e.g. NNN.do.DESCRIPTION.sql 

csasm::DATABASE=> UPDATE schemaversion SET md5 = '6e96ccfcbec43520e4ed7bf0566bc536' WHERE version = 2;
UPDATE 1
csasm::DATABASE=> UPDATE schemaversion SET md5 = 'c876d8de73b15303f8f7b08f10c3590b' WHERE version = 3;
UPDATE 1
csasm::DATABASE=> UPDATE schemaversion SET md5 = '639e29f1504535c892dbb1a431fef2a7' WHERE version = 5;
UPDATE 1


Your database has the following tables (found using below query via heroku pg:psql -a csasm)

SELECT *
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog' AND 
    schemaname != 'information_schema';

csasm::DATABASE->     schemaname != 'information_schema';
 schemaname |    tablename    |   tableowner   | tablespace | hasindexes | hasrules | hastriggers | rowsecurity
------------+-----------------+----------------+------------+------------+----------+-------------+-------------
 public     | schemaversion   | oamwpgahehkldp |            | t          | f        | f           | f
 public     | spatial_ref_sys | postgres       |            | t          | f        | f           | f
 public     | geocaches       | oamwpgahehkldp |            | t          | f        | f           | f
 public     | games           | oamwpgahehkldp |            | t          | f        | t           | f
 public     | waypoint        | oamwpgahehkldp |            | t          | f        | t           | f
 public     | players         | oamwpgahehkldp |            | t          | f        | t           | f
 public     | player          | oamwpgahehkldp |            | t          | f        | t           | f
 public     | asm             | oamwpgahehkldp |            | t          | f        | f           | f
(8 rows)

**Comment by Pprime1** [comment]
thankyou. Only using 'games', 'waypoint' and 'player' (no s) currently. Will leave it alone though now.

**Comment by Pprime1** [comment]
created a second game for a second set of test cases. postgrator 008 refers.  (in my Set-occupied branch currently). 
New issue is that the display-query is now returning null results. So I presume this means the new 008 postgrator file is killing it. So sounds like I need to learn how to do a schema update. The heroku website console is not it apparently.

**Comment by judsona** [comment]
I don’t think so. Might be we aren’t passing game id into query? Maybe if it didn’t apply sql it would crash completely saying something is wrong with the sql

**Comment by Pprime1** [comment]
this is the same error I was getting earlier in this same issue when I tried to delete the unneeded .sql files. The whole database is not loading and so the querys are returning null values ... leading to errors in the client.js. 
So just trying to create a new sql file using the name convention specified ie:  008.do.new_game_GCALBURY.sql  fails. And deleting that file again doesn't help, it's screwed again. :-( 

So the whole database aspect and schemaversion md5 keys is another whole world universe to try and get my head into. Probably starting with how to run commands.  And if the UPDATE commands above are safe to run still?

Perhaps I can create a dataclip if it's a repeatable command:
https://data.heroku.com/datastores/77fca8e8-9cf7-44cc-82ca-dbc71276a3d4#dataclips

**Comment by Pprime1** [comment]
**Continuing research in to how to fix the escalating problems.**
I think a Dataclip would allow me to run a series of updates to the schema so as to correct the md5 values which have somehow changed now. ie: 
```
csasm::DATABASE=> UPDATE schemaversion SET md5 = '6e96ccfcbec43520e4ed7bf0566bc536' WHERE version = 2;
UPDATE 1
```
in order to work out what the md5 value should now be for each table I need to run a console command (cannot get console commands to run currently) something like in https://stackoverflow.com/questions/63581945/how-to-fix-error-md5-checksum-failed-for-migration-1-npm-err-code-elifecycle
`md5 004.do.asm-table.sql`  to get the current md5 value back.
This might work in a local run heroku cli command prompt - nothing works in the web console.

**Comment by Pprime1** [comment]
no, doesn't work in a heroku cli command prompt window either.

**Comment by judsona** [comment]
are you able to let me know exactly what it is saying when it boots? I'm not able to find anything wrong with current setup, and the heroku instance is running properly

**Comment by judsona** [comment]
Ahhh - I see 

2021-06-03T10:17:56.095375+00:00 app[web.1]: Updating Room: group-GCTEST With Location Statuses
2021-06-03T10:17:56.101741+00:00 app[web.1]: []
2021-06-03T10:17:56.101978+00:00 app[web.1]: There are Promise { <pending> } outside function
2021-06-03T10:17:56.105938+00:00 app[web.1]: There are undefined inside function

I'm going to download the code and try see if it does it for me

**Comment by Pprime1** [comment]
There are no errors, but the call in server.js line 42 to get data from a database table is now returning nul entry - as is every other call to get data from a table. Saw this before last time I tried to do anything to the postgrator directory (that time I was deleting redundant code). This time I had tried adding a new file (008) to allow a second game to test different things with. Can't recover from doing anything in postgrator it seems.

**Comment by Pprime1** [comment]
ok, thanks. I need to get the database working again before I can even bother trying to work out how to count rows and manipulate anything prior to trying to work out the success routines

**Comment by judsona** [comment]
I'm booting app now to see what is going on :-)

**Comment by judsona** [comment]
I think I need to re-write a small section to allow for async functions... i'm trying to give it a go now

**Comment by judsona** [comment]
Also a quick note

Anytime you have string with replacement inside e.g. ${game_code} that string must be surrounded by backtick

**Comment by judsona** [comment]
@Pprime1 look server.js now in the set occupied state branch.. I've reformatted the code to allow for async method and using the await code within them.

**Comment by Pprime1** [comment]
OK, thanks. Will take me some time to work out how this works again.  
Still will need to work out the original question that caused this issue: How I can add a new game to the database. eg: csasm/postgrator_008_GCALBURY-game.sql (and there will be others in the future) into the postgrator directory so it loads.

**Comment by Pprime1** [comment]
**> retrieved md5 for each sql and compared to database, then applied differences, and restarted app dynos to confirm it is now running. :-)**
> Any future sql changes to database should create a new sql file e.g. NNN.do.DESCRIPTION.sql

> csasm::DATABASE=> UPDATE schemaversion SET md5 = '6e96ccfcbec43520e4ed7bf0566bc536' WHERE version = 2;
UPDATE 1
> csasm::DATABASE=> UPDATE schemaversion SET md5 = 'c876d8de73b15303f8f7b08f10c3590b' WHERE version = 3;
UPDATE 1
> csasm::DATABASE=> UPDATE schemaversion SET md5 = '639e29f1504535c892dbb1a431fef2a7' WHERE version = 5;
UPDATE 1

OK, to close this issue, I think, I now need to learn how to retrieve the md5 for each sql and then update the database schemaversion values to match with the commands listed here.

**Comment by Pprime1** [comment]
also, seems I cannot update a database load file if there's a minor correction I need to make? (GCAlbury Albury waypoint coords need to be slightly amended.) Even in a branch any changes I make are just ignored.

**Comment by Pprime1** [comment]
closing this issue as matters have morphed a bit. New issue raised for tracking progress towards resolution
